### ISSUE TITLE
Get-Prediction Fails 

### ISSUE THREAD

**Issue by trevorNgo** [TriageCapacityPlanning/Testable-Artifiact#32]
Receiving 500 Internal server error no matter the input used in the Interval-Prediction page.
![image](https://user-images.githubusercontent.com/23327878/110214771-2101bc00-7e74-11eb-80c0-0916d9925134.png)
![image](https://user-images.githubusercontent.com/23327878/110214799-42fb3e80-7e74-11eb-8a9c-75b4afa3b1e3.png)

Possible Cause:
Inspecting flask server response, it would appear on prediction failure in the `predict()` method in `TriageController.py`, possibly sim_results is the NoneType:
![image](https://user-images.githubusercontent.com/23327878/110214862-9ff6f480-7e74-11eb-9c1f-bc50ac228a56.png)

`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/src/app/api/resources/predict.py", line 85, in get
    predictions = triage_controller.predict()
  File "/usr/src/app/api/common/controller/TriageController.py", line 118, in predict
    } for sim_result in zip(sim_results, self.intervals)]
TypeError: 'NoneType' object is not iterable`

Severity: Medium
Reproduction:
Setup via Docker-compose build... and Docker run...
To get around Stict-cross-origin I use cross-origin resource sharing extension by Moesif.
I then input values into the interval-prediction page as shown in screenshot above.
I inspect the server response via chrome dev tools.

**Comment by trevorNgo** [comment]
Exact html server response attached below.
(Adding .txt to file so that github will accept filetype upload. Remove to view in browser with proper styling)
[ServerErrorResponse.html.txt](https://github.com/TriageCapacityPlanning/Triage-Testable-Artifact/files/6095757/ServerErrorResponse.html.txt)

**Comment by Rubinstd** [comment]
This bug has been fixed
